Repository time-rs/time, pull requests merged in 2022-06, with the labels that each got.

#468 Implement concise `Display` repr for `Duration`
  src/duration.rs
  tests/integration/duration.rs
Labels: A-core, C-enhancement

#478 Fix incorrect RFC3339 offset parsing
  src/parsing/parsable.rs
  tests/integration/parsing.rs
Labels: C-bug, C-keep-open, A-parsing, A-well-known-format-description

#473 Parse nulls as None on nested serde structs
  src/serde/visitor.rs
  tests/integration/serde/mod.rs
  tests/integration/serde/rfc2822.rs
  tests/integration/serde/rfc3339.rs
Labels: A-parsing, C-enhancement, A-well-known-format-description
